kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: webdev-access
  namespace: dev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: webdev-access
subjects:
- kind: User
  namespace: webdev
  name: groupObjectId
