kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: apidev-access
  namespace: apidev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: apidev-access
subjects:
- kind: User
  namespace: apidev
  name: groupObjectId
