# This is a SecretProviderClass example using aad-pod-identity to access the key vault
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azkv-team4
spec:
  provider: azure
  parameters:
    usePodIdentity: "true"               # Set to true for using aad-pod-identity to access your key vault
    keyvaultName: team4-kv       # Set to the name of your key vault
    cloudName: ""                        # [OPTIONAL for Azure] if not provided, the Azure environment defaults to AzurePublicCloud
    objects:  |
      array:
        - |
          objectName: SQLUSER
          objectType: secret
          objectAlias: SQL_USER
        - |
          objectName: SQLPASSWORD
          objectType: secret
          objectAlias: SQL_PASSWORD
        - |
          objectName: SQLSERVER
          objectType: secret
          objectAlias: SQL_SERVER
        - |
          objectName: SQLDB
          objectType: secret
          objectAlias: SQL_DBNAME
    tenantId: 929aed32-c7e4-4b5f-babc-c7905ae7f9eb