apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
   app: poi
  name: poi
spec:
  containers:
  - image: registryawm8866.azurecr.io/tripinsights/poi:1.0
    name: poi
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}

---
apiVersion: v1
kind: Service
metadata:
  name: poi
spec:
  ports:
  - port: 80
  selector:
    app: poi
