apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    app: tripviewer
  name: tripviewer
spec:
  containers:
  - image: registryawm8866.azurecr.io/tripinsights/tripviewer:1.0
    name: tripviewer
    env:
    - name: USERPROFILE_API_ENDPOINT
      value: http://userprofile
    - name: TRIPS_API_ENDPOINT
      value: http://trips
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}

---
apiVersion: v1
kind: Service
metadata:
  name: tripviewer
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: tripviewer