apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: trips
  name: trips
spec:
  containers:
  - image: registryawm8866.azurecr.io/tripinsights/trips:1.0
    name: trips
    env:
    - name: SQL_USER
      value: sqladminaWm8866
    - name: SQL_PASSWORD
      value: SQL@4life
    - name: SQL_DBNAME
      value: mydrivingDB
    - name: SQL_SERVER
      value: sqlserverawm8866.database.windows.net
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
