apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    app: tripviewer
  name: tripviewer
  namespace: webdev
spec:
  containers:
  - image: registryawm8866.azurecr.io/tripinsights/tripviewer:1.0
    name: tripviewer
    env:
    - name: USERPROFILE_API_ENDPOINT
      value: http://userprofile.apidev
    - name: TRIPS_API_ENDPOINT
      value: http://trips.apidev
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}

---
apiVersion: v1
kind: Service
metadata:
  name: tripviewer
  namespace: webdev
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: tripviewer

---
apiVersion: v1
kind: Service
metadata:
  name: tripviewer-ilb
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
  namespace: webdev
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: tripviewer