apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: trips
  name: trips
spec:
  containers:
  - image: registryawm8866.azurecr.io/tripinsights/trips:1.0
    name: trips
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
