apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: userprofile
  name: userprofile
spec:
  containers:
  - image: registryawm8866.azurecr.io/tripinsights/userprofile:1.0
    name: userprofile
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
